version: "3.8"
services:
  app:
    container_name: server
    restart: always
    build: .
    volumes:
      - .:/app
      - ignore:/app/env/
    env_file:
      - .env
    ports:
      - 80:8000
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

volumes:
  ignore:
